apiVersion: rbac.authorization.k8s.io/v1alpha1
kind: ClusterRole
metadata:
  name: {{ template "fullname" . }}
rules:
- apiGroups: ["extensions", "app"]
  resources: 
  - deployments
  - replicasets
  - ingresses
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: 
  - horizontalpodautoscalers
  verbs: ["*"]
- apiGroups: [""]
  resources: 
  - namespaces
  - events
  - replicationcontrollers
  - serviceaccounts
  - configmaps
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["*"]
